//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace calc.MyMathOperations {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/MathsLibrary")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyMathOperations.IMathOperations")]
    public interface IMathOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMathOperations/GetDataUsingDataContractResponse")]
        calc.MyMathOperations.CompositeType GetDataUsingDataContract(calc.MyMathOperations.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMathOperations/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<calc.MyMathOperations.CompositeType> GetDataUsingDataContractAsync(calc.MyMathOperations.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Add", ReplyAction="http://tempuri.org/IMathOperations/AddResponse")]
        int Add(int v1, int v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Add", ReplyAction="http://tempuri.org/IMathOperations/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int v1, int v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Multiply", ReplyAction="http://tempuri.org/IMathOperations/MultiplyResponse")]
        int Multiply(int v1, int v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Multiply", ReplyAction="http://tempuri.org/IMathOperations/MultiplyResponse")]
        System.Threading.Tasks.Task<int> MultiplyAsync(int v1, int v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Substract", ReplyAction="http://tempuri.org/IMathOperations/SubstractResponse")]
        int Substract(int v1, int v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Substract", ReplyAction="http://tempuri.org/IMathOperations/SubstractResponse")]
        System.Threading.Tasks.Task<int> SubstractAsync(int v1, int v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Divide", ReplyAction="http://tempuri.org/IMathOperations/DivideResponse")]
        double Divide(int v1, int v2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMathOperations/Divide", ReplyAction="http://tempuri.org/IMathOperations/DivideResponse")]
        System.Threading.Tasks.Task<double> DivideAsync(int v1, int v2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMathOperationsChannel : calc.MyMathOperations.IMathOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MathOperationsClient : System.ServiceModel.ClientBase<calc.MyMathOperations.IMathOperations>, calc.MyMathOperations.IMathOperations {
        
        public MathOperationsClient() {
        }
        
        public MathOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MathOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MathOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public calc.MyMathOperations.CompositeType GetDataUsingDataContract(calc.MyMathOperations.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<calc.MyMathOperations.CompositeType> GetDataUsingDataContractAsync(calc.MyMathOperations.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int Add(int v1, int v2) {
            return base.Channel.Add(v1, v2);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int v1, int v2) {
            return base.Channel.AddAsync(v1, v2);
        }
        
        public int Multiply(int v1, int v2) {
            return base.Channel.Multiply(v1, v2);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyAsync(int v1, int v2) {
            return base.Channel.MultiplyAsync(v1, v2);
        }
        
        public int Substract(int v1, int v2) {
            return base.Channel.Substract(v1, v2);
        }
        
        public System.Threading.Tasks.Task<int> SubstractAsync(int v1, int v2) {
            return base.Channel.SubstractAsync(v1, v2);
        }
        
        public double Divide(int v1, int v2) {
            return base.Channel.Divide(v1, v2);
        }
        
        public System.Threading.Tasks.Task<double> DivideAsync(int v1, int v2) {
            return base.Channel.DivideAsync(v1, v2);
        }
    }
}
