//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikingHeavyClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRestStationsAndItinary", ReplyAction="http://tempuri.org/IService1/GetRestStationsAndItinaryResponse")]
        System.IO.Stream GetRestStationsAndItinary(double x, double y, double x2, double y2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetRestStationsAndItinary", ReplyAction="http://tempuri.org/IService1/GetRestStationsAndItinaryResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetRestStationsAndItinaryAsync(double x, double y, double x2, double y2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSoapStationsAndItinary", ReplyAction="http://tempuri.org/IService1/GetSoapStationsAndItinaryResponse")]
        string GetSoapStationsAndItinary(double x, double y, double x2, double y2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSoapStationsAndItinary", ReplyAction="http://tempuri.org/IService1/GetSoapStationsAndItinaryResponse")]
        System.Threading.Tasks.Task<string> GetSoapStationsAndItinaryAsync(double x, double y, double x2, double y2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : BikingHeavyClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<BikingHeavyClient.ServiceReference1.IService1>, BikingHeavyClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream GetRestStationsAndItinary(double x, double y, double x2, double y2) {
            return base.Channel.GetRestStationsAndItinary(x, y, x2, y2);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetRestStationsAndItinaryAsync(double x, double y, double x2, double y2) {
            return base.Channel.GetRestStationsAndItinaryAsync(x, y, x2, y2);
        }
        
        public string GetSoapStationsAndItinary(double x, double y, double x2, double y2) {
            return base.Channel.GetSoapStationsAndItinary(x, y, x2, y2);
        }
        
        public System.Threading.Tasks.Task<string> GetSoapStationsAndItinaryAsync(double x, double y, double x2, double y2) {
            return base.Channel.GetSoapStationsAndItinaryAsync(x, y, x2, y2);
        }
    }
}
